"""FP8 quantization utilities for weight sync from Megatron to SGLang.

Quantizes BF16 weights to FP8 (e4m3) with blockwise quantization
before sending to SGLang via weight sync. Uses SGLang's own
per_block_cast_to_fp8 for bit-identical results with SGLang inference.

References:
  - slime/backends/megatron_utils/megatron_to_hf/processors/quantizer_fp8.py
  - sglang/srt/layers/quantization/fp8_utils.py
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import torch
from sglang.srt.layers.quantization.fp8_utils import per_block_cast_to_fp8

logger = logging.getLogger(__name__)

# FP8 E4M3 constants
FP8_DTYPE = torch.float8_e4m3fn
FP8_MAX = torch.finfo(FP8_DTYPE).max  # 448.0
FP8_MIN = -FP8_MAX


# ---------- Layer name matching ----------
# Uses modules_to_not_convert from quantization_config (generated by model publisher)
# and weight_scale_inv entries from model.safetensors.index.json as ground truth.


def _should_quantize(
    name: str,
    modules_to_not_convert: list[str] | None = None,
    fp8_weight_names: set[str] | None = None,
) -> bool:
    """Check if a parameter should be quantized to FP8.

    Uses two sources of truth (in priority order):
    1. fp8_weight_names: Set of weight names that are actually FP8 in the checkpoint
       (derived from model.safetensors.index.json). This is the most reliable source.
    2. modules_to_not_convert: Exclusion list from quantization_config (fallback).
    """
    if not name.endswith(".weight"):
        return False

    if fp8_weight_names is not None and len(fp8_weight_names) > 0:
        return name in fp8_weight_names

    if modules_to_not_convert:
        for skip_module in modules_to_not_convert:
            if skip_module in name:
                return False

    return True


def _quantize_single_param(name: str, weight: torch.Tensor) -> list[tuple[str, torch.Tensor]]:
    """Quantize a single weight tensor to FP8 using SGLang's blockwise quantization.

    Returns list of (name, tensor) pairs: the quantized weight + its scale.
    """
    if weight.ndim != 2:
        return [(name, weight)]

    qweight, scale = per_block_cast_to_fp8(weight)
    scale_name = name.replace(".weight", ".weight_scale_inv")
    return [(name, qweight), (scale_name, scale)]


# ---------- Main quantization entry point ----------


def load_quantization_config(model_path: str | Path) -> dict | None:
    """Load quantization_config from model's config.json.

    Also loads the weight map from model.safetensors.index.json to determine
    which weights are actually stored as FP8 (have a corresponding weight_scale_inv).

    Returns None if the model is not quantized or doesn't have FP8 config.
    """
    model_path = Path(model_path)
    config_path = model_path / "config.json"
    if not config_path.exists():
        return None

    with config_path.open() as f:
        config = json.load(f)

    qconfig = config.get("quantization_config")
    if qconfig is None:
        return None

    if qconfig.get("quant_method") != "fp8":
        return None

    # Load weight map to find which weights have FP8 scale tensors (ground truth).
    fp8_weight_names: set[str] = set()
    index_path = model_path / "model.safetensors.index.json"
    if index_path.exists():
        with index_path.open() as f:
            index = json.load(f)
        weight_map = index.get("weight_map", {})
        for key in weight_map:
            if key.endswith((".weight_scale_inv", ".weight_scale")):
                base_name = key.rsplit(".", 1)[0] + ".weight"
                fp8_weight_names.add(base_name)
        logger.info(f"Loaded FP8 weight map: {len(fp8_weight_names)} quantized weights out of {len(weight_map)} total entries")
    else:
        logger.warning(f"No model.safetensors.index.json found at {model_path}, will use modules_to_not_convert only")

    qconfig["_fp8_weight_names"] = fp8_weight_names
    return qconfig


def quantize_params_for_fp8(
    named_tensors: list[tuple[str, torch.Tensor]],
    quantization_config: dict,
) -> list[tuple[str, torch.Tensor]]:
    """Quantize a batch of named tensors to FP8 based on quantization_config.

    Returns list of (name, tensor) pairs with quantizable weights replaced by
    (weight_fp8, scale) pairs.
    """
    modules_to_not_convert = quantization_config.get("modules_to_not_convert")
    fp8_weight_names = quantization_config.get("_fp8_weight_names")

    result = []
    n_quantized = 0
    for name, tensor in named_tensors:
        if _should_quantize(name, modules_to_not_convert, fp8_weight_names):
            result.extend(_quantize_single_param(name, tensor))
            n_quantized += 1
        else:
            result.append((name, tensor))

    if n_quantized == 0 and fp8_weight_names and len(fp8_weight_names) > 0:
        sample_names = [n for n, _ in named_tensors[:3]]
        sample_fp8 = sorted(fp8_weight_names)[:3]
        logger.warning(
            f"FP8 quantization: 0 weights quantized out of {len(named_tensors)}! Sample bridge names: {sample_names}, Sample FP8 names: {sample_fp8}"
        )

    return result
